// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqxUM2hf2FWL-A83o5L_cSnyn4BYqyuQ',
    appId: '1:271942246701:web:5250652c0f75e080c4f3a4',
    messagingSenderId: '271942246701',
    projectId: 'palenque-application-49f39',
    authDomain: 'palenque-application-49f39.firebaseapp.com',
    storageBucket: 'palenque-application-49f39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATYXMKrn2eiouGeC4hq8xYP6wf-SSrcI',
    appId: '1:271942246701:android:d1dd66f1cd03bcbcc4f3a4',
    messagingSenderId: '271942246701',
    projectId: 'palenque-application-49f39',
    storageBucket: 'palenque-application-49f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZE37EOGbe19RQKVQ13mBg1D7qSsCe3k',
    appId: '1:271942246701:ios:870ca42f49dfefeac4f3a4',
    messagingSenderId: '271942246701',
    projectId: 'palenque-application-49f39',
    storageBucket: 'palenque-application-49f39.firebasestorage.app',
    iosBundleId: 'com.example.palenqueApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZE37EOGbe19RQKVQ13mBg1D7qSsCe3k',
    appId: '1:271942246701:ios:870ca42f49dfefeac4f3a4',
    messagingSenderId: '271942246701',
    projectId: 'palenque-application-49f39',
    storageBucket: 'palenque-application-49f39.firebasestorage.app',
    iosBundleId: 'com.example.palenqueApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJqxUM2hf2FWL-A83o5L_cSnyn4BYqyuQ',
    appId: '1:271942246701:web:d71cac244170e1d0c4f3a4',
    messagingSenderId: '271942246701',
    projectId: 'palenque-application-49f39',
    authDomain: 'palenque-application-49f39.firebaseapp.com',
    storageBucket: 'palenque-application-49f39.firebasestorage.app',
  );
}
